### ISSUE TITLE
Java is missing from mcr.microsoft.com/vscode/devcontainers/java:0.205.18-11

### ISSUE THREAD

**Issue by etienne-chrp** [devcontainers/images#339] opened 2023-01-18 09:32 UTC
The Java image mcr.microsoft.com/vscode/devcontainers/java:0.205.18-11 is not containing Java.

Can be tested with the following commands:

`docker run --rm mcr.microsoft.com/vscode/devcontainers/java:0.205.18-11 java --version` : `"java": executable file not found in $PATH: unknown.`

`docker run --rm mcr.microsoft.com/vscode/devcontainers/java:0.205.17-11 java --version` : `openjdk 11.0.17 2022-10-18 LTS`

I had a look at the history of the Java folder but did not really find anything relevant... https://github.com/devcontainers/images/commits/main/src/java

**Comment by samruddhikhandale** [comment] 2023-01-18 23:53
Hi 👋 

Thanks for reporting. Looks like https://github.com/devcontainers/images/commit/a872849f0ef8a7c06069612351eb93b6270bb050 is the cause for it. 
When the images are published, 17 gets published before 11 in a same workflow job. For some reason, 11 is caching the dockerfile & is not executing any commands. Hence, there is no java available. Looking into fixing it.

https://github.com/devcontainers/images/actions/runs/3943846478/jobs/6749144892#step:6:1385

**Comment by oalper** [comment] 2023-01-19 13:31
Not only it does not contain java, ENV variables are also pointing to incorrect places... i.e.

JAVA_HOME=/usr/local/sdkman/candidates/java/current
where as it should be in :
/usr/lib/jvm/msopenjdk-current/

**Comment by samruddhikhandale** [comment] 2023-01-20 17:22
The bug is fixed in the latest java release -`mcr.microsoft.com/vscode/devcontainers/java:0.205.19-11`

**Closed by samruddhikhandale** 2023-01-20 17:22 UTC
Labels: bug

**Comment by oalper** [comment] 2023-01-20 17:50
```
$ printenv JAVA_HOME
/usr/local/sdkman/candidates/java/current

This is still incorrect...

$ ls -l /usr/local/sdkman/candidates/java/
ls: cannot access '/usr/local/sdkman/candidates/java/': No such file or directory

$ which java
/usr/lib/jvm/msopenjdk-current/bin/java
```

**Comment by samruddhikhandale** [comment] 2023-01-20 22:01
@oalper Thanks, it's definitely a bug.
Created https://github.com/devcontainers/images/issues/368 for tracking.
