### ISSUE TITLE
go pkgs cannot be installed in latest universal image

### ISSUE THREAD

**Issue by pdeva** [devcontainers/images#405] opened 2023-02-04 20:48 UTC
steps to reproduce:

1. create Github Codespace using devcontainer that uses `mcr.microsoft.com/devcontainers/universal:2-focal` image
2. create a golang project with some dependencies in your go.mod file.
3. run `go get -u ./...`

you will get errors like:

```
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/jackc: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/coreos: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/kr: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/konsorten: permission denied
```

seems `/go/pkg` is now owned and writable by `root` only. so now noone can use Golang on GIthub Codespaces due to this....

**Comment by samruddhikhandale** [comment] 2023-02-06 22:17
Hi 👋 

Unfortunately, I couldn't reproduce with this dev config 👇 

```jsonc
{
	"image": "mcr.microsoft.com/devcontainers/universal:2"
}
```

![image](https://user-images.githubusercontent.com/24955913/217099820-054f5dcf-cbce-4bad-b962-7d1d8ccbde04.png)

![image](https://user-images.githubusercontent.com/24955913/217099897-32d0031b-0fdd-4d11-a62d-d0f5f0704869.png)

The permissions look good to me, can you paste the output from `devcontainer-info` command and also your entire dev config?

**Comment by pdeva** [comment] 2023-02-07 19:48
[devcontainer.zip](https://github.com/devcontainers/images/files/10678836/devcontainer.zip)
attaching our devcontainer config files

output of command you requested:

```
@pdeva ➜ /workspaces/monorepo (main) $ devcontainer-info

Development container image information

- Image version: 2.2.3
- Definition ID: universal
- Source code repository: https://github.com/devcontainers/images
- Source code release/branch: v0.2.39
- Timestamp: Wed, 25 Jan 2023 00:09:56 GMT

More info: https://github.com/devcontainers/images/tree/main/src/universal/history/2.2.3.md

@pdeva ➜ /workspaces/monorepo (main) $
```

**Comment by pdeva** [comment] 2023-02-07 19:52
also the permissions you are looking at are in `/usr/local/go`, but if you notice my OP, it seems it refers to `/go` which is where GOPATH seems to  points to by default in the  `mcr.microsoft.com/devcontainers/universal:2-focal` image

**Comment by samruddhikhandale** [comment] 2023-02-07 23:23
Tried to reproduce with the dev container linked above, however, it is failing to install the `ghcr.io/rio/features/kustomize` Feature. Hence, the dev container fails to build.

I tried commenting out and rebuilding but still facing some other issues.

@pdeva does the dev container build fine for you? Also, can you provide the version of the dev containers extension?

**Comment by pdeva** [comment] 2023-02-08 00:17
working fine for us. we just put this dir in our repo and let github codespaces build it..

**Comment by pdeva** [comment] 2023-02-08 05:07
[logs_1072.zip](https://github.com/devcontainers/images/files/10681836/logs_1072.zip)
attaching log of succesfully creating a github codespaces prebuild using the devcontainer config i gave you eariler

**Comment by joshspicer** [comment] 2023-02-08 20:31
👋  @pdeva - Also trying to repro and I can't seem to see what you're seeing. From your config it looks like you're doing a fair amount of modification on top of the universal image. Do you think anything in your Dockerfile, or perhaps the Features, could be changing the permissions of that `go/` directory?

<img width="1799" alt="image" src="https://user-images.githubusercontent.com/23246594/217643493-8c822781-a433-4c6c-97b1-7c2d20d1d9af.png">

If you're able to isolate the issue to a more minimal config (smaller dockerfile and/or less Features), that would be helpful for us to provide better advise for you.

**Comment by pdeva** [comment] 2023-02-08 23:40
let us try to isolate this to a minimal config and get back to yoy

**Comment by pdeva** [comment] 2023-02-10 19:12
We have the minimal reproducible config now:

`devcontainer.json`:
```json
{
	"name": "AstradotUbuntu",
	"build": {
            "dockerfile": "Dockerfile"
    }
}

```

`Dockerfile` :
```docker
FROM mcr.microsoft.com/devcontainers/universal:2-focal

RUN go install github.com/google/wire/cmd/wire@latest
```


it seems running the `go install` command in the `Dockerfile` changes the permission of the `/go` folder for some reason. Its unclear why this would happen tho. `go install` doesnt change permissions, just downloads files to relevant directories..

**Comment by samruddhikhandale** [comment] 2023-02-10 19:25
Thanks! I was able to reproduce the error with this dev config.

> RUN go install github.com/google/wire/cmd/wire@latest

This command is running as `root` instead of the image's `remoteUser: codespace`, and that's what causing the issues.

I was able to get things working with by setting `USER codespace` before the `go install...` command👇 

Dockerfile
``` 
FROM mcr.microsoft.com/devcontainers/universal:2-focal

USER codespace
RUN go install github.com/google/wire/cmd/wire@latest
```

@pdeva do you mind giving this a try?

**Comment by pdeva** [comment] 2023-02-10 22:18
the issue goes away when i use  `USER codespace` indeed! 😃 
i wonder why running as `root` causes the entire `go/pkg` folder path to change ownership to `root' tho... 🤔

**Comment by samruddhikhandale** [comment] 2023-02-14 23:05
Closing as resolved.

**Closed by samruddhikhandale** 2023-02-14 23:05 UTC
Labels: needs-more-info
