### ISSUE TITLE
ruby gems extensions subdirectory not writable in mcr.microsoft.com/devcontainers/universal:2.3.0

### ISSUE THREAD

**Issue by nathanweeks** [devcontainers/images#551] opened 2023-05-01 11:55 UTC
The default ruby (3.1.4) gems extensions x86_64-linux subdirectory is not group writable in mcr.microsoft.com/devcontainers/universal:2.3.0. Installing gems that attempt to write to this directory as the `codespace` user results in a file system permission error:

```
$ docker run -it --rm --entrypoint=/bin/bash --user=codespace mcr.microsoft.com/devcontainers/universal:2.3.0
codespace ➜ / $ ls -ld /usr/local/rvm/gems/ruby-3.1.4/extensions
drwxrwsr-x 1 codespace rvm 4096 Apr 21 05:09 /usr/local/rvm/gems/ruby-3.1.4/extensions
codespace ➜ / $ ls -l /usr/local/rvm/gems/ruby-3.1.4/extensions/
total 4
drwxr-sr-x 3 root rvm 4096 Apr 21 05:09 x86_64-linux
codespace ➜ / $ gem install racc
Fetching racc-1.6.2.gem
Building native extensions. This could take a while...
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /usr/local/rvm/gems/ruby-3.1.4/extensions/x86_64-linux/3.1.0/racc-1.6.2
        /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir'
```

In mcr.microsoft.com/devcontainers/universal:2.2.9, this directory was group-writable:
```
$ docker run -it --rm --entrypoint=/bin/bash --user=codespace mcr.microsoft.com/devcontainers/universal:2.2.9
codespace ➜ / $ ls -l /usr/local/rvm/gems/ruby-3.1.3/extensions/
total 8
drwxrwsr-x 1 codespace rvm 4096 Mar 13 19:53 x86_64-linux
codespace ➜ / $ gem install racc
Fetching racc-1.6.2.gem
Building native extensions. This could take a while...
Successfully installed racc-1.6.2
Parsing documentation for racc-1.6.2
Installing ri documentation for racc-1.6.2
Done installing documentation for racc after 0 seconds
1 gem installed
codespace ➜ / $
```

I suspect the permission issue may have been introduced in src/universal/.devcontainer/local-features/jekyll/install.sh, which after installing jekyll adjusts the permissions of installed executables in the gem/bin directory, but does not adjust the permissions of installed library files/directories: 

https://github.com/devcontainers/images/blob/2b47c86df5994512f59af170ddb7eb1644f5ab08/src/universal/.devcontainer/local-features/jekyll/install.sh#L22-L32

*Speculation*: I'm guessing this specific issue didn't impact mcr.microsoft.com/devcontainers/universal:2.2.9 as the /usr/local/rvm/gems/ruby-3.1.3/extensions/x86_64-linux may been populated before the jekyll/install.sh script executes (by a feature installed beforehand; e.g., ghcr.io/devcontainers/features/ruby:1), as it contains other libraries with appropriate group ownership (and in particular, the parent extensions/x86_64-linux directory is group writable), while in mcr.microsoft.com/devcontainers/universal:2.3.0 it looks like extensions/x86_64-linux may contain only libraries installed by the jekyll/install.sh script (i.e., the extensions/x86_64-linux directory may have been created by the execution of that script).

**Comment by samruddhikhandale** [comment] 2023-05-02 16:22
Hi 👋 

Thanks for reporting this issue, @alexander-smolyakov can you take a look at this one?

**Comment by alexander-smolyakov** [comment] 2023-05-03 14:14
Hey @nathanweeks, the issue related to the changes that were made to the `ghcr.io/devcontainers/features/ruby` feature recently:
- https://github.com/devcontainers/features/pull/505

I'm going to check these changes and apply the fix. I will update the ticket once the issue is fixed.

**Comment by alexander-smolyakov** [comment] 2023-05-12 11:21
The fix for devcontainer merged. The fix will be available in the next release.

**Closed by alexander-smolyakov** 2023-05-12 11:21 UTC
