### ISSUE TITLE
NODE_OPTIONS being set incorrectly in VS Code integrated terminal

### ISSUE THREAD

**Issue by danfarinoeyecue** [devcontainers/images#501] opened 2023-03-22 22:16 UTC
The integrated terminal in VS Code, when running in a Codespace, is setting `NODE_OPTIONS=undefined`

This does not happen when connecting to the codespace using `gh cs ssh`, only in the integrated terminal.

@jcansdale confirmed that this is an issue with the `mcr.microsoft.com/devcontainers/universal:2` container image.

**Comment by samruddhikhandale** [comment] 2023-03-23 22:34
Hi 👋 

Thanks for reporting, I could reproduce the issue on a codespace which uses the default image (ie universal)

![image](https://user-images.githubusercontent.com/24955913/227377605-82f90cb1-3bae-4e63-9b50-8263ef9bc867.png)

In both scenarios (connecting to a codespace in web vs with gh cs ssh), I am connecting to the same codespace which has the exact same `universal` image. Hence, I don't think the issue is with the universal image, however, looks like the `NODE_OPTIONS` variable gets added somewhere in the flow of opening a codespace in web/desktop as opposed to ssh.

Also, I created a container with this image, where NODE_OPTIONS is empty. 👇 

![image](https://user-images.githubusercontent.com/24955913/227378571-61dcf8a9-067d-4e31-a032-7e7eb4dc916a.png)

@jcansdale should we open a tracking issue for Codespaces instead?

**Comment by danfarinoeyecue** [comment] 2023-03-23 23:33
Hi Samruddhi, thanks for taking a look.

In my codespace, I traced it back to this ancestor process (i.e. walking up the tree from bash, this is the topmost process that still had `NODE_OPTIONS=undefined`). Its command line is:

```
sh /home/vscode/.vscode-remote/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/server.sh --log trace --force-disable-user-env --server-data-dir /home/vscode/.vscode-remote --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-secret /home/vscode/.vscode-remote/data/Machine/.connection-token-ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 --extensions-download-dir /home/vscode/.vscode-remote/extensionsCache --start-server  --enable-remote-auto-shutdown
```

My suspicion is a file named `/home/vscode/.vscode-remote/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/extensions/ms-vscode.js-debug/src/bootloader.bundle.js` which is minified JavaScript. I can see it contains the string `NODE_OPTIONS:void 0`, which could explain this behavior. I'm not 100% sure this file is actually involved, but it is in that same directory, which makes me suspicious.

**Comment by samruddhikhandale** [comment] 2023-04-05 23:17
I have opened a tracking issue on Codespaces side for this issue. Also, note that this issue is not related to a specific image but happens in any Codespace.

I'd update here once the issue is fixed, thanks!

**Comment by jkeech** [comment] 2023-05-23 16:02
This issue should be fixed now. Let us know if you continue to see `NODE_OPTIONS=undefined` still being set in VS Code integrated terminals.

**Closed by jkeech** 2023-05-23 16:02 UTC
