### ISSUE TITLE
didn't notice this before. But even the workspace folder have permission issues

### ISSUE THREAD

**Issue by Xboxis** [devcontainers/images#159] opened 2022-10-13 16:30 UTC
didn't notice this before. But even the workspace folder have permission issues

```zsh
@snebjorn ➜ /workspaces/openapi-generator (feature/devcontainer ✗) $ ls
ls: cannot access 'Vagrantfile': Operation not permitted
ls: cannot access 'docs': Operation not permitted
ls: cannot access 'samples': Operation not permitted
ls: cannot access 'bin': Operation not permitted
ls: cannot access 'CODE_OF_CONDUCT.md': Operation not permitted
ls: cannot access 'new.sh': Operation not permitted
ls: cannot access 'docker-compose.yml': Operation not permitted
ls: cannot access 'scripts': Operation not permitted
ls: cannot access 'LICENSE': Operation not permitted
ls: cannot access 'appveyor.yml': Operation not permitted
ls: cannot access 'modules': Operation not permitted
ls: cannot access 'README.md': Operation not permitted
ls: cannot access 'CONTRIBUTING.md': Operation not permitted
ls: cannot access 'google_checkstyle.xml': Operation not permitted
ls: cannot access 'spotbugs-exclude.xml': Operation not permitted
ls: cannot access 'docker-entrypoint.sh': Operation not permitted
ls: cannot access 'bitrise.yml': Operation not permitted
ls: cannot access 'mvnw': Operation not permitted
ls: cannot access 'website': Operation not permitted
ls: cannot access 'sec.gpg.enc': Operation not permitted
ls: cannot access 'shippable.yml': Operation not permitted
ls: cannot access 'openapi-generator.code-workspace': Operation not permitted
ls: cannot access 'CI': Operation not permitted
ls: cannot access 'pom.xml': Operation not permitted
ls: cannot access 'mvnw.cmd': Operation not permitted
ls: cannot access 'run-in-docker.sh': Operation not permitted
ls: cannot access 'Dockerfile': Operation not permitted
appveyor.yml  bitrise.yml  CODE_OF_CONDUCT.md  docker-compose.yml    Dockerfile  google_checkstyle.xml  modules  mvnw.cmd  openapi-generator.code-workspace  README.md         samples  sec.gpg.enc    spotbugs-exclude.xml  website
bin           CI           CONTRIBUTING.md     docker-entrypoint.sh  docs        LICENSE                mvnw     new.sh    pom.xml                           run-in-docker.sh  scripts  shippable.yml  Vagrantfile
@snebjorn ➜ /workspaces/openapi-generator (feature/devcontainer ✗) $ whoami
vscode
@snebjorn ➜ /workspaces/openapi-generator (feature/devcontainer ✗) $ 
```

_Originally posted by @snebjorn in https://github.com/devcontainers/images/issues/155#issuecomment-1272512525_

**Comment by bamurtaugh** [comment] 2022-10-26 22:10
It seems this is a subset / duplicate of another issue. But if I'm missing something, please let me know. Thanks!

**Closed by bamurtaugh** 2022-10-26 22:10 UTC
